# This file created by conda-build 3.21.6
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Tue Nov  9 20:01:03 2021
# ------------------------------------------------

package:
  name: libffi
  version: 3.4.2
source:
  patches:
    - 0001-arm64-use-a-dedicated-dylib-for-trampolines-so-it-ca.patch
    - 0002-Add-support-for-ffi_find_closure_for_code_np-on-Appl.patch
  sha256: 540fb721619a6aba3bdeef7d940d8e9e0e6d2c193595bc243241b77ff9e93620
  url: https://github.com/libffi/libffi/releases/download/v3.4.2/libffi-3.4.2.tar.gz
build:
  number: '5'
  run_exports:
    - libffi >=3.4,<4.0a0
  string: h3422bc3_5
requirements:
  build:
    - autoconf 2.69 pl5321hc0e15e3_11
    - automake 1.16.5 pl5321h694c41f_0
    - cctools_osx-64 949.0.1 h6407bdd_23
    - cctools_osx-arm64 949.0.1 h55de48a_23
    - clang 11.1.0 h694c41f_1
    - clang-11 11.1.0 default_he082bbe_1
    - clang_osx-arm64 11.1.0 h40be2b1_4
    - clangxx 11.1.0 default_he082bbe_1
    - compiler-rt 11.1.0 h654b07c_0
    - compiler-rt_osx-64 11.1.0 h8c5fa43_0
    - ld64_osx-64 530 he8994da_21
    - ld64_osx-arm64 530 h3681fde_21
    - ldid 2.1.2 h6a69015_3
    - libclang-cpp11.1 11.1.0 default_he082bbe_1
    - libcxx 12.0.1 habf9029_0
    - libiconv 1.16 haf1e3a3_0
    - libllvm11 11.1.0 hd011deb_2
    - libllvm12 12.0.1 hd011deb_2
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.11 h9173be1_1013
    - llvm-tools 11.1.0 hd011deb_2
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - ncurses 6.2 h2e338ed_4
    - patch 2.7.6 hbcf498f_1002
    - perl 5.32.1 1_h0d85af4_perl5
    - tapi 1100.0.11 h9ce4665_0
    - texinfo 6.8 pl5321hb877abe_1
    - zlib 1.2.11 h9173be1_1013
  host: []
  run: []
test:
  commands:
    - test -e $PREFIX/lib/libffi${SHLIB_EXT}
    - test -e $PREFIX/lib/libffi.a
    - test -e $PREFIX/include/ffi.h
    - test -e $PREFIX/include/ffitarget.h
  requires: null
about:
  description: 'The libffi library provides a portable, high level programming interface

    to various calling conventions. This allows a programmer to call any

    function specified by a call interface description at run-time.

    '
  dev_url: https://github.com/libffi/libffi
  doc_url: https://sourceware.org/libffi/
  home: https://sourceware.org/libffi/
  license: MIT
  license_file: LICENSE
  summary: A Portable Foreign Function Interface Library.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - scopatz
    - stefan-balke
