# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: libsqlite
  version: 3.46.0
source:
  patches: null
  sha256: 6f8e6a7b335273748816f9b3b62bbdc372a889de8782d7f048c653a447417a7d
  url: https://www.sqlite.org/2024/sqlite-autoconf-3460000.tar.gz
build:
  number: 0
  run_exports:
    - libsqlite >=3.46.0,<4.0a0
  string: hfb93653_0
requirements:
  build:
    - ca-certificates 2024.6.2 h8857fd0_0
    - cctools_osx-64 986 ha1c5b94_0
    - cctools_osx-arm64 986 h7bb7a8e_0
    - clang 16.0.6 hd4457cd_7
    - clang-16 16.0.6 default_h4c8afb6_7
    - clang_impl_osx-arm64 16.0.6 ha81d56d_16
    - clang_osx-arm64 16.0.6 h40be2b1_16
    - clangxx 16.0.6 default_ha3b9224_7
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 711 ha20a434_0
    - ld64_osx-arm64 711 h6aa3cc8_0
    - libclang-cpp16 16.0.6 default_h4c8afb6_7
    - libcxx 17.0.6 h88467a6_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.12.7 h3e169fe_1
    - libzlib 1.3.1 h87427d6_1
    - llvm-tools 16.0.6 hbedff68_3
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - make 4.3 h22f3db7_1
    - openssl 3.3.1 h87427d6_0
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - libzlib 1.2.13 hfb2fe0b_6
    - zlib 1.2.13 hfb2fe0b_6
  run:
    - __osx >=11.0
    - libzlib >=1.2.13,<2.0a0
test:
  commands:
    - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
    - test ! -f $PREFIX/lib/libsqlite3.a
    - test -f $PREFIX/include/sqlite3.h
    - test -f $PREFIX/include/sqlite3ext.h
about:
  description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

    public-domain, SQL database engine.It is the most used database engine

    in the world.

    '
  dev_url: https://github.com/mackyle/sqlite
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  doc_url: http://www.sqlite.org/docs.html
  home: http://www.sqlite.org/
  license: Unlicense
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240610.1.1
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
  remote_url: https://github.com/conda-forge/sqlite-feedstock
  sha: 01d86159255f61a51a83c0c37250ef10918e5f60
