# This file created by conda-build 24.5.0
# ------------------------------------------------

package:
  name: libzlib
  version: 1.3.1
source:
  sha256: 9a93b2b7dfdac77ceba5a558a580e74667dd6fede4585b91eefb60f03b72df23
  url:
    - http://zlib.net/zlib-1.3.1.tar.gz
    - https://gnupg.org/ftp/gcrypt/zlib/zlib-1.3.1.tar.gz
build:
  number: 1
  run_exports:
    - libzlib >=1.3.1,<2.0a0
  string: hfb2fe0b_1
requirements:
  build:
    - clang_bootstrap_osx-arm64 16.0.6 h223edda_15
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
  run_constrained:
    - zlib 1.3.1 *_1
test:
  commands:
    - test ! -f ${PREFIX}/lib/libz.a
    - test ! -f ${PREFIX}/lib/libz${SHLIB_EXT}
    - test ! -f ${PREFIX}/include/zlib.h
about:
  description: 'zlib is designed to be a free, general-purpose, lossless data-compression

    library for use on virtually any computer hardware and operating system.

    '
  dev_url: https://github.com/madler/zlib
  doc_url: http://zlib.net/manual.html
  home: http://zlib.net/
  license: Zlib
  license_family: Other
  license_file: license.txt
  summary: Massively spiffy yet delicately unobtrusive compression library
extra:
  copy_test_source_files: true
  feedstock-name: zlib
  final: true
  flow_run_id: azure_20240528.2.1
  recipe-maintainers:
    - groutr
    - isuruf
    - msarahan
    - ocefpaf
  remote_url: https://github.com/conda-forge/zlib-feedstock
  sha: 93de2148ef571eb6f44a971dd61f6d466af9a8a1
