# This file created by conda-build 24.7.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Aug  4 18:41:54 2024
# ------------------------------------------------

package:
  name: wheel
  version: 0.44.0
source:
  sha256: a29c3f2817e95ab89aa4660681ad547c0e9547f20e75b0562fe7723c9a2a9d49
  url: https://pypi.io/packages/source/w/wheel/wheel-0.44.0.tar.gz
build:
  entry_points:
    - wheel = wheel.cli:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/wheel_1722797001595/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -c "import flit_core.buildapi; flit_core.buildapi.build_wheel('.')" && /home/conda/feedstock_root/build_artifacts/wheel_1722797001595/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m installer --no-compile-bytecode wheel-*.whl
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h4bc722e_7
    - ca-certificates 2024.7.4 hbcca054_0
    - flit-core 3.9.0 pyhd8ed1ab_1
    - ld_impl_linux-64 2.40 hf3520f5_7
    - libexpat 2.6.2 h59595ed_0
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 14.1.0 h77fa898_0
    - libgomp 14.1.0 h77fa898_0
    - libnsl 2.0.1 hd590300_0
    - libsqlite 3.46.0 hde9e2c9_0
    - libuuid 2.38.1 h0b41bf4_0
    - libxcrypt 4.4.36 hd590300_1
    - libzlib 1.3.1 h4ab18f5_1
    - ncurses 6.5 h59595ed_0
    - openssl 3.3.1 h4bc722e_2
    - python 3.12.4 h194c7f8_0_cpython
    - python-installer 0.7.0 pyhd8ed1ab_0
    - readline 8.2 h8228510_1
    - tk 8.6.13 noxft_h4845f30_101
    - tzdata 2024a h0c530f3_0
    - xz 5.2.6 h166bdaf_0
  run:
    - python >=3.8
test:
  commands:
    - pip check
    - wheel --help
  imports:
    - wheel
    - wheel.cli
  requires:
    - pip
about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240804.2.1
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/wheel-feedstock
  sha: 511ade36b75b266973d257b91df0a86409af5d02
