CI: azure
CONDA_BUILD_SYSROOT: /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
MACOSX_DEPLOYMENT_TARGET: '11.0'
MACOSX_SDK_VERSION: '11.0'
build_platform: osx-64
bzip2: '1'
c_compiler: clang
c_compiler_version: '16'
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: clangxx
cxx_compiler_version: '16'
extend_keys:
- ignore_build_only_deps
- ignore_version
- extend_keys
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
libffi: '3.4'
lua: '5'
macos_machine: arm64-apple-darwin20.0.0
ncurses: '6'
numpy: '1.16'
openssl: '3'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
python: '3.10'
python_impl: cpython
r_base: '3.5'
readline: '8'
sqlite: '3'
target_platform: osx-arm64
tk: '8.6'
xz: '5'
zip_keys:
- - c_compiler_version
  - cxx_compiler_version
zlib: '1.2'
