# This file created by conda-build 24.1.2
# ------------------------------------------------

package:
  name: python
  version: 3.10.14
source:
  - md5: 05148354ce821ba7369e5b7958435400
    patches:
      - patches/0001-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0002-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0003-Support-cross-compiling-byte-code.patch
      - patches/0004-bpo-45258-search-for-isysroot-in-addition-to-sysroot.patch
      - patches/0005-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0006-Win32-Do-not-download-externals.patch
      - patches/0007-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0008-bpo-22699-Allow-compiling-on-debian-ubuntu-with-a-di.patch
      - patches/0009-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0010-Unvendor-openssl.patch
      - patches/0011-Unvendor-sqlite3.patch
      - patches/0012-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0013-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0014-Add-d1trimfile-SRC_DIR-to-make-pdbs-more-relocatable.patch
      - patches/0015-Doing-d1trimfile.patch
      - patches/0016-cross-compile-darwin.patch
      - patches/0017-Fix-TZPATH-on-windows.patch
      - patches/0018-Make-dyld-search-work-with-SYSTEM_VERSION_COMPAT-1.patch
      - patches/0019-Fix-LDSHARED-when-CC-is-overriden-on-Linux-too.patch
      - patches/0020-Unvendor-bzip2.patch
      - patches/0021-Unvendor-libffi.patch
      - patches/0022-Unvendor-tcltk.patch
      - patches/0023-unvendor-xz.patch
      - patches/0024-unvendor-zlib.patch
      - patches/0025-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
    url: https://www.python.org/ftp/python/3.10.14/Python-3.10.14.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports_from:
    - clangxx_osx-arm64 16.*
  no_link: null
  number: 0
  run_exports:
    noarch:
      - python
    weak:
      - python_abi 3.10.* *_cp310
  script_env:
    - CONDA_FORGE=yes
    - PY_INTERP_DEBUG=no
    - PY_INTERP_LINKAGE_NATURE=static
  skip_compile_pyc:
    - '*.py'
  string: h2469fbe_0_cpython
requirements:
  build:
    - ca-certificates 2024.2.2 h8857fd0_0
    - cctools_osx-64 986 ha1c5b94_0
    - cctools_osx-arm64 986 h7bb7a8e_0
    - clang 16.0.6 hdae98eb_5
    - clang-16 16.0.6 default_h7151d67_5
    - clang_impl_osx-arm64 16.0.6 ha81d56d_10
    - clang_osx-arm64 16.0.6 h40be2b1_10
    - clangxx 16.0.6 default_h7151d67_5
    - clangxx_impl_osx-arm64 16.0.6 h4a79b72_10
    - clangxx_osx-arm64 16.0.6 h40be2b1_10
    - compiler-rt 16.0.6 ha38d28d_2
    - compiler-rt_osx-64 16.0.6 ha38d28d_2
    - icu 73.2 hf5e326d_0
    - ld64_osx-64 711 ha20a434_0
    - ld64_osx-arm64 711 h6aa3cc8_0
    - libclang-cpp16 16.0.6 default_h7151d67_5
    - libcxx 16.0.6 hd57cbcb_0
    - libiconv 1.17 hd75f5a5_2
    - libllvm16 16.0.6 hbedff68_3
    - libtool 2.4.7 hf0c8a7f_0
    - libxml2 2.12.6 hc0ae0f7_0
    - libzlib 1.2.13 h8a1eda9_5
    - llvm-tools 16.0.6 hbedff68_3
    - make 4.3 h22f3db7_1
    - openssl 3.2.1 hd75f5a5_1
    - pkg-config 0.29.2 ha3d46e9_1008
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.5 h829000d_0
  host:
    - bzip2 1.0.8 h93a5062_5
    - ca-certificates 2024.2.2 hf0a4a13_0
    - libffi 3.4.2 h3422bc3_5
    - libsqlite 3.45.2 h091b4b1_0
    - libzlib 1.2.13 h53f4e23_5
    - ncurses 6.4.20240210 h078ce10_0
    - openssl 3.2.1 h0d3ecfb_1
    - readline 8.2 h92ec313_1
    - sqlite 3.45.2 hf2abe2d_0
    - tk 8.6.13 h5083fa2_1
    - xz 5.2.6 h57fd34a_0
    - zlib 1.2.13 h53f4e23_5
  run:
    - bzip2 >=1.0.8,<2.0a0
    - libffi >=3.4,<4.0a0
    - libsqlite >=3.45.2,<4.0a0
    - libzlib >=1.2.13,<1.3.0a0
    - ncurses >=6.4.20240210,<7.0a0
    - openssl >=3.2.1,<4.0a0
    - readline >=8.2,<9.0a0
    - tk >=8.6.13,<8.7.0a0
    - tzdata
    - xz >=5.2.6,<6.0a0
  run_constrained:
    - python_abi 3.10.* *_cp310
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -c "from zoneinfo import ZoneInfo; from datetime import datetime; dt
      = datetime(2020, 10, 31, 12, tzinfo=ZoneInfo('America/Los_Angeles')); print(dt.tzname())"
    - python -m venv test-venv
    - test-venv/bin/python -c "import ctypes"
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.10.14
    - popd
    - popd
    - python run_test.py
    - test ! -f default.profraw
    - test -d "$PREFIX/lib/python3.1/site-packages"
    - python3.1 --version
    - python -c "from ctypes import CFUNCTYPE; CFUNCTYPE(None)(id)"
    - TERM=xterm >/dev/null python -c "import curses; scr = curses.initscr(); curses.unget_wch('x');
      assert 'x' ==  scr.get_wch()"
    - python -c "import crypt"
  downstreams:
    - cython
    - setuptools
  files:
    - run_test.py
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils/*
    - tests/prefix-replacement/*
  requires:
    - clang_osx-arm64 16.*
    - clangxx_osx-arm64 16.*
    - cmake
    - ninja
    - ripgrep
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  flow_run_id: azure_20240320.5.1
  recipe-maintainers:
    - isuruf
    - jakirkham
    - katietz
    - mbargull
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
    - xhochy
  remote_url: https://github.com/conda-forge/python-feedstock
  sha: a0c0223f2f67cd7bfc6542df394afc65f9fa069f
