# This file created by conda-build 24.5.1
# ------------------------------------------------

package:
  name: openssl
  version: 3.3.1
source:
  patches:
    - patches/0001-Give-util-mkinstallvars.pl-more-fine-grained-control.patch
    - patches/0002-Adapt-all-the-exporter-files-to-the-new-vars-from-ut.patch
    - patches/0003-Fix-cmake-generator.patch
  sha256: 777cd596284c883375a2a7a11bf5d2786fc5413255efab20c50d6ffe6d020b7e
  url: http://www.openssl.org/source/openssl-3.3.1.tar.gz
build:
  no_link: lib/libcrypto.3.0.dylib
  number: 2
  run_exports:
    - openssl >=3.3.1,<4.0a0
  string: hfb2fe0b_2
requirements:
  build:
    - clang_bootstrap_osx-arm64 16.0.6 h223edda_17
    - macosx_deployment_target_osx-arm64 11.0 h6553868_1
    - make 4.3 h22f3db7_1
    - perl 5.32.1 7_h10d778d_perl5
  host:
    - __osx >=11.0
  run:
    - __osx >=11.0
    - ca-certificates
  run_constrained:
    - pyopenssl >=22.1
test:
  commands:
    - touch checksum.txt
    - $PREFIX/bin/openssl sha256 checksum.txt
    - pkg-config --print-errors --exact-version "3.3.1" openssl
    - if [[ "$(pkg-config --variable=prefix openssl)" == "" ]]; then exit 1; else
      exit 0; fi
  requires:
    - pkg-config
    - ripgrep
about:
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man3.0/
  home: http://www.openssl.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  feedstock-name: openssl
  final: true
  flow_run_id: azure_20240717.2.1
  recipe-maintainers:
    - h-vetinari
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/openssl-feedstock
  sha: 101ec411cb85d1002db7b07617634278e74ba3a2
