# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Feb  2 15:10:23 2024
# ------------------------------------------------

package:
  name: tzdata
  version: 2024a
source:
  - sha256: 0d0434459acbd2059a7a8da1f3304a84a86591f6ed69c6248fffa502b6edffe3
    url: https://data.iana.org/time-zones/releases/tzdata2024a.tar.gz
  - sha256: 80072894adff5a458f1d143e16e4ca1d8b2a122c9c5399da482cb68cba6a1ff8
    url: https://data.iana.org/time-zones/releases/tzcode2024a.tar.gz
build:
  ignore_run_exports:
    - libgcc-ng
  noarch: generic
  number: '0'
  string: h0c530f3_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 h69a702a_13
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_2
    - gcc_impl_linux-64 12.3.0 he2b93b0_5
    - gcc_linux-64 12.3.0 h76fc315_2
    - kernel-headers_linux-64 3.10.0 h4a8ded7_13
    - ld_impl_linux-64 2.40 h41732ed_0
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_105
    - libgcc-ng 13.2.0 h807b86a_5
    - libgomp 13.2.0 h807b86a_5
    - libsanitizer 12.3.0 h0f45ef3_5
    - libstdcxx-ng 13.2.0 h7e041cc_5
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.17 h4a8ded7_13
  host:
    - __glibc >=2.17,<3.0.a0
  run: []
test:
  commands:
    - test -f "${PREFIX}/share/zoneinfo/leapseconds"
    - test -f "${PREFIX}/share/zoneinfo/iso3166.tab"
    - test -f "${PREFIX}/share/zoneinfo/zone1970.tab"
    - test -f "${PREFIX}/share/zoneinfo/zone.tab"
    - test -f "${PREFIX}/share/zoneinfo/tzdata.zi"
    - "dirs=\"$(\n  find \"${PREFIX}\" -mindepth 1 -maxdepth 2 \\\n  \\! -path \"\
      ${PREFIX}/share\" \\! -path \"${PREFIX}/conda-meta*\"\n)\"\ntest \"${dirs}\"\
      \ = \"${PREFIX}/share/zoneinfo\"\n"
    - "heads=\"$(\n  find \"${PREFIX}/share/zoneinfo\" -type f \\\n    \\! -name \\\
      *.zi \\! -name \\*.tab \\! -name leapseconds \\\n    -exec head -c4 {} \\; -printf\
      \ \\\\n \\\n    | uniq\n)\"\ntest \"${heads}\" = TZif\n"
about:
  description: 'The Time Zone Database (called tz, tzdb or zoneinfo) contains code

    (the tzcode package) and data (this package) that represent the

    history of local time for many representative

    locations around the globe.  It is updated periodically to reflect

    changes made by political bodies to time zone boundaries, UTC offsets,

    and daylight-saving rules.

    '
  dev_url: https://github.com/eggert/tz
  doc_url: https://data.iana.org/time-zones/tz-link.html
  home: https://www.iana.org/time-zones
  license: LicenseRef-Public-Domain
  license_file: LICENSE
  summary: The Time Zone Database (called tz, tzdb or zoneinfo) data
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240202.1.1
  recipe-maintainers:
    - mbargull
    - ocefpaf
    - pganssle
  remote_url: https://github.com/conda-forge/tzdata-feedstock
  sha: b05633457f40064273acc6b623583b7fdbade083
