# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipe, last modified Fri Aug 12 23:22:54 2022
# ------------------------------------------------

package:
  name: xz
  version: 5.2.6
source:
  patches:
    - 0001-Add-vs2008-support-via-cmake.patch
    - 0002-Add-gettimeofday-for-VS2008.patch
  sha256: 13e3402e301b6018f6a71ef0e497f714c6d11e214ae82dab156b81c2a64acb25
  url: http://downloads.sourceforge.net/project/lzmautils/xz-5.2.6.tar.bz2
build:
  number: '0'
  run_exports:
    - xz >=5.2.6,<6.0a0
  string: h57fd34a_0
requirements:
  build:
    - autoconf 2.69 pl5321hc0e15e3_11
    - automake 1.16.5 pl5321h694c41f_0
    - ca-certificates 2022.6.15 h033912b_0
    - cctools_osx-64 973.0.1 h3eff9a4_10
    - cctools_osx-arm64 973.0.1 h98580c8_10
    - clang 13.0.1 h694c41f_0
    - clang-13 13.0.1 default_he082bbe_0
    - clang_osx-arm64 13.0.1 hdd0e76e_2
    - clangxx 13.0.1 default_he082bbe_0
    - compiler-rt 13.0.1 he01351e_0
    - compiler-rt_osx-64 13.0.1 hd3f61c9_0
    - ld64_osx-64 609 h6fbe7a8_10
    - ld64_osx-arm64 609 hee039ab_10
    - libclang-cpp13 13.0.1 default_he082bbe_0
    - libcxx 14.0.6 hce7ea42_0
    - libllvm13 13.0.1 h64f94b2_2
    - libllvm14 14.0.6 h41df66c_0
    - libtool 2.4.6 he49afe7_1008
    - libzlib 1.2.12 hfe4f2af_2
    - llvm-tools 13.0.1 h64f94b2_2
    - m4 1.4.18 haf1e3a3_1001
    - make 4.3 h22f3db7_1
    - openssl 3.0.5 hb81d4ab_1
    - perl 5.32.1 2_h0d85af4_perl5
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
  host: []
  run: []
about:
  description: 'XZ Utils is free general-purpose data compression software with a
    high

    compression ratio. XZ Utils were written for POSIX-like systems, but also

    work on some not-so-POSIX systems.

    '
  dev_url: http://git.tukaani.org/
  doc_source_url: https://github.com/xz-mirror/xz/blob/master/README
  doc_url: http://tukaani.org/xz/
  home: http://tukaani.org/xz/
  license: LGPL-2.1 and GPL-2.0
  license_file: COPYING
  summary: Data compression software with high compression ratio
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - nehaljwani
    - ocefpaf
    - scopatz
